"""empty message

Revision ID: f6dd7b788254
Revises: 
Create Date: 2023-11-13 22:45:51.073693

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6dd7b788254'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=512), nullable=False),
    sa.Column('mode', sa.Enum('super_admin', 'admin', 'agent', name='adminmode'), nullable=False),
    sa.Column('can_add_admin', sa.Boolean(), nullable=False),
    sa.Column('max_users', sa.Integer(), nullable=False),
    sa.Column('max_active_users', sa.Integer(), nullable=False),
    sa.Column('comment', sa.String(length=512), nullable=True),
    sa.Column('telegram_id', sa.String(length=512), nullable=True),
    sa.Column('parent_admin_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parent_admin_id'], ['admin_user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_table('child',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('unique_id', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('unique_id')
    )
    op.create_table('parent_domain',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('domain', sa.String(length=200), nullable=False),
    sa.Column('alias', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('domain')
    )
    op.create_table('bool_config',
    sa.Column('child_id', sa.Integer(), nullable=False),
    sa.Column('key', sa.Enum('ssh_server_redis_url', 'ssh_server_port', 'ssh_server_enable', 'first_setup', 'core_type', 'warp_enable', 'warp_mode', 'warp_plus_code', 'warp_sites', 'dns_server', 'reality_fallback_domain', 'reality_server_names', 'reality_short_ids', 'reality_private_key', 'reality_public_key', 'reality_port', 'restls1_2_domain', 'restls1_3_domain', 'show_usage_in_sublink', 'cloudflare', 'license', 'country', 'package_mode', 'utls', 'telegram_bot_token', 'is_parent', 'parent_panel', 'unique_id', 'last_hash', 'cdn_forced_host', 'lang', 'admin_lang', 'admin_secret', 'tls_ports', 'http_ports', 'kcp_ports', 'kcp_enable', 'decoy_domain', 'proxy_path', 'firewall', 'netdata', 'http_proxy_enable', 'block_iran_sites', 'allow_invalid_sni', 'auto_update', 'speed_test', 'only_ipv4', 'shared_secret', 'telegram_enable', 'telegram_adtag', 'telegram_lib', 'telegram_fakedomain', 'v2ray_enable', 'torrent_block', 'ssfaketls_enable', 'ssfaketls_fakedomain', 'shadowtls_enable', 'shadowtls_fakedomain', 'tuic_enable', 'tuic_port', 'hysteria_enable', 'hysteria_port', 'ssr_enable', 'ssr_fakedomain', 'vmess_enable', 'domain_fronting_domain', 'domain_fronting_http_enable', 'domain_fronting_tls_enable', 'db_version', 'branding_title', 'branding_site', 'branding_freetext', 'not_found', 'path_vmess', 'path_vless', 'path_trojan', 'path_v2ray', 'path_ss', 'path_ws', 'path_tcp', 'path_grpc', name='configenum'), nullable=False),
    sa.Column('value', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['child_id'], ['child.id'], ),
    sa.PrimaryKeyConstraint('child_id', 'key')
    )
    op.create_table('daily_usage',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('usage', sa.BigInteger(), nullable=False),
    sa.Column('online', sa.Integer(), nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=False),
    sa.Column('child_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['admin_user.id'], ),
    sa.ForeignKeyConstraint(['child_id'], ['child.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('domain',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('child_id', sa.Integer(), nullable=True),
    sa.Column('domain', sa.String(length=200), nullable=False),
    sa.Column('alias', sa.String(length=200), nullable=True),
    sa.Column('sub_link_only', sa.Boolean(), nullable=False),
    sa.Column('mode', sa.Enum('direct', 'sub_link_only', 'cdn', 'auto_cdn_ip', 'relay', 'reality', 'old_xtls_direct', 'worker', 'fake', name='domaintype'), nullable=False),
    sa.Column('cdn_ip', sa.Text(length=2000), nullable=True),
    sa.Column('grpc', sa.Boolean(), nullable=True),
    sa.Column('servernames', sa.String(length=1000), nullable=True),
    sa.ForeignKeyConstraint(['child_id'], ['child.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('proxy',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('child_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('enable', sa.Boolean(), nullable=False),
    sa.Column('proto', sa.Enum('vless', 'trojan', 'vmess', 'ss', 'v2ray', 'ssr', 'ssh', 'tuic', 'hysteria2', name='proxyproto'), nullable=False),
    sa.Column('l3', sa.Enum('tls', 'tls_h2', 'tls_h2_h1', 'h3_quic', 'reality', 'http', 'kcp', 'ssh', 'custom', name='proxyl3'), nullable=False),
    sa.Column('transport', sa.Enum('h2', 'grpc', 'XTLS', 'faketls', 'shadowtls', 'restls1_2', 'restls1_3', 'WS', 'tcp', 'ssh', 'custom', name='proxytransport'), nullable=False),
    sa.Column('cdn', sa.Enum('CDN', 'direct', 'Fake', name='proxycdn'), nullable=False),
    sa.ForeignKeyConstraint(['child_id'], ['child.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('str_config',
    sa.Column('child_id', sa.Integer(), nullable=False),
    sa.Column('key', sa.Enum('ssh_server_redis_url', 'ssh_server_port', 'ssh_server_enable', 'first_setup', 'core_type', 'warp_enable', 'warp_mode', 'warp_plus_code', 'warp_sites', 'dns_server', 'reality_fallback_domain', 'reality_server_names', 'reality_short_ids', 'reality_private_key', 'reality_public_key', 'reality_port', 'restls1_2_domain', 'restls1_3_domain', 'show_usage_in_sublink', 'cloudflare', 'license', 'country', 'package_mode', 'utls', 'telegram_bot_token', 'is_parent', 'parent_panel', 'unique_id', 'last_hash', 'cdn_forced_host', 'lang', 'admin_lang', 'admin_secret', 'tls_ports', 'http_ports', 'kcp_ports', 'kcp_enable', 'decoy_domain', 'proxy_path', 'firewall', 'netdata', 'http_proxy_enable', 'block_iran_sites', 'allow_invalid_sni', 'auto_update', 'speed_test', 'only_ipv4', 'shared_secret', 'telegram_enable', 'telegram_adtag', 'telegram_lib', 'telegram_fakedomain', 'v2ray_enable', 'torrent_block', 'ssfaketls_enable', 'ssfaketls_fakedomain', 'shadowtls_enable', 'shadowtls_fakedomain', 'tuic_enable', 'tuic_port', 'hysteria_enable', 'hysteria_port', 'ssr_enable', 'ssr_fakedomain', 'vmess_enable', 'domain_fronting_domain', 'domain_fronting_http_enable', 'domain_fronting_tls_enable', 'db_version', 'branding_title', 'branding_site', 'branding_freetext', 'not_found', 'path_vmess', 'path_vless', 'path_trojan', 'path_v2ray', 'path_ss', 'path_ws', 'path_tcp', 'path_grpc', name='configenum'), nullable=False),
    sa.Column('value', sa.String(length=2048), nullable=True),
    sa.ForeignKeyConstraint(['child_id'], ['child.id'], ),
    sa.PrimaryKeyConstraint('child_id', 'key')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=512), nullable=False),
    sa.Column('last_online', sa.DateTime(), nullable=False),
    sa.Column('expiry_time', sa.Date(), nullable=True),
    sa.Column('usage_limit', sa.BigInteger(), nullable=False),
    sa.Column('package_days', sa.Integer(), nullable=False),
    sa.Column('mode', sa.Enum('no_reset', 'monthly', 'weekly', 'daily', name='usermode'), nullable=False),
    sa.Column('monthly', sa.Boolean(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('current_usage', sa.BigInteger(), nullable=False),
    sa.Column('last_reset_time', sa.Date(), nullable=True),
    sa.Column('comment', sa.String(length=512), nullable=True),
    sa.Column('telegram_id', sa.String(length=512), nullable=True),
    sa.Column('added_by', sa.Integer(), nullable=True),
    sa.Column('max_ips', sa.Integer(), nullable=False),
    sa.Column('enable', sa.Boolean(), nullable=False),
    sa.Column('lang', sa.Enum('en', 'fa', 'ru', 'pt', 'zh', name='lang'), nullable=True),
    sa.Column('ed25519_private_key', sa.String(length=500), nullable=True),
    sa.Column('ed25519_public_key', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['added_by'], ['admin_user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_table('show_domain',
    sa.Column('domain_id', sa.Integer(), nullable=False),
    sa.Column('related_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['domain_id'], ['domain.id'], ),
    sa.ForeignKeyConstraint(['related_id'], ['domain.id'], ),
    sa.PrimaryKeyConstraint('domain_id', 'related_id'),
    info={'bind_key': None}
    )
    op.create_table('show_domain_parent',
    sa.Column('domain_id', sa.Integer(), nullable=False),
    sa.Column('related_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['domain_id'], ['parent_domain.id'], ),
    sa.ForeignKeyConstraint(['related_id'], ['domain.id'], ),
    sa.PrimaryKeyConstraint('domain_id', 'related_id'),
    info={'bind_key': None}
    )
    op.create_table('user_detail',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('child_id', sa.Integer(), nullable=False),
    sa.Column('last_online', sa.DateTime(), nullable=False),
    sa.Column('current_usage', sa.BigInteger(), nullable=False),
    sa.Column('connected_ips', sa.String(length=512), nullable=False),
    sa.ForeignKeyConstraint(['child_id'], ['child.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_detail')
    op.drop_table('show_domain_parent')
    op.drop_table('show_domain')
    op.drop_table('user')
    op.drop_table('str_config')
    op.drop_table('proxy')
    op.drop_table('domain')
    op.drop_table('daily_usage')
    op.drop_table('bool_config')
    op.drop_table('parent_domain')
    op.drop_table('child')
    op.drop_table('admin_user')
    # ### end Alembic commands ###
