"""Server outbounds: where matching traffic leaves the server (WARP, direct, block, SOCKS, Tor, Psiphon)."""

from __future__ import annotations

import re
from collections.abc import Iterable
from enum import auto
from typing import TYPE_CHECKING, Any

from sqlalchemy import Enum, String, Text
from sqlalchemy.orm import Mapped, mapped_column
from sqlalchemy.types import JSON
from strenum import StrEnum

from hiddifypanel.database import db

if TYPE_CHECKING:
    from hiddifypanel.models.external_model.outbound import OutboundModel


class OutboundMode(StrEnum):
    warp = auto()
    psiphon = auto()
    direct = auto()
    socks = auto()
    tor = auto()
    block = auto()
    #: The admin's own JSON: hiddify-core ``{"outbounds": [...]}``, hiddify-core ``{"endpoints": [...]}`` or xray ``{"outbounds": [...]}``.
    #: The other core reaches them through a local SOCKS bridge (see proxy_v3.outbound_custom).
    core_outbound = auto()
    core_endpoint = auto()
    xray_outbound = auto()


#: Built in on every panel; can not be deleted.
BUILTIN_MODES = (OutboundMode.warp, OutboundMode.direct, OutboundMode.block)
#: Modes that may exist more than once.
MULTI_MODES = (OutboundMode.socks, OutboundMode.core_outbound, OutboundMode.core_endpoint, OutboundMode.xray_outbound)
#: Modes whose body is the admin's own JSON (the ``config`` column).
CUSTOM_CONFIG_MODES = (OutboundMode.core_outbound, OutboundMode.core_endpoint, OutboundMode.xray_outbound)
#: Modes that connect to a SOCKS endpoint.
ENDPOINT_MODES = (OutboundMode.socks, OutboundMode.tor, OutboundMode.psiphon, *CUSTOM_CONFIG_MODES)
#: Of those, only SOCKS is configured by the admin; Tor and Psiphon use the local ports of the defaults file.
CONFIGURABLE_ENDPOINT_MODES = (OutboundMode.socks,)
#: Order given to outbounds from before they could be reordered: blocking first, exits, WARP, direct.
RULE_ORDER = (OutboundMode.block, OutboundMode.socks, *CUSTOM_CONFIG_MODES, OutboundMode.tor, OutboundMode.psiphon, OutboundMode.warp, OutboundMode.direct)

#: Routing list fields an admin can edit.
LIST_FIELDS = ("sites", "geosites", "rule_sets")


class Outbound(db.Model):  # type: ignore
    __tablename__ = "outbound"

    id: Mapped[int] = mapped_column(primary_key=True, autoincrement=True)
    #: Stable name shared by the parent, its nodes and backups (ids are local and autogenerated).
    slug: Mapped[str] = mapped_column(String(100), unique=True, default="")
    name: Mapped[str] = mapped_column(String(100))
    mode: Mapped[OutboundMode] = mapped_column(Enum(OutboundMode))
    enabled: Mapped[bool] = mapped_column(default=True)
    #: Rule order (1 = checked first). The last enabled outbound is the default (route final).
    position: Mapped[int | None] = mapped_column(default=None)
    #: Kept equal to "last enabled" (see proxy_v3.outbounds.finalize).
    is_default: Mapped[bool] = mapped_column(default=False)
    #: Also route the panel region's domestic sites here.
    domestic: Mapped[bool] = mapped_column(default=False)

    #: Domains (matched with subdomains).
    sites: Mapped[list[Any] | None] = mapped_column(JSON, default=list)
    #: xray geosite tags.
    geosites: Mapped[list[Any] | None] = mapped_column(JSON, default=list)
    #: hiddify-core rule-set names or URLs.
    rule_sets: Mapped[list[Any] | None] = mapped_column(JSON, default=list)

    host: Mapped[str | None] = mapped_column(String(255), default="")
    port: Mapped[int | None] = mapped_column(default=None)
    username: Mapped[str | None] = mapped_column(String(255), default="")
    password: Mapped[str | None] = mapped_column(String(255), default="")
    #: Custom modes: the admin's JSON text (validated before it is stored).
    config: Mapped[str | None] = mapped_column(Text, default="")

    is_builtin: Mapped[bool] = mapped_column(default=False)
    #: The defaults file's lists (and `domestic`) at the last sync: refreshed on upgrade.
    builtin_lists: Mapped[dict[str, Any] | None] = mapped_column(JSON, default=dict)
    #: The admin edited the lists: upgrades no longer replace them.
    lists_override: Mapped[bool] = mapped_column(default=False)

    @staticmethod
    def make_slug(name: str, mode: OutboundMode | str, taken: set[str] | None = None) -> str:
        """A free slug: the mode for built-ins' first outbound, else ``<mode>-<name>``; numbered when taken."""
        base = re.sub(r"[^a-z0-9]+", "-", f"{mode}-{name}".lower()).strip("-")[:90] or str(mode)
        used = set(taken or ()) | {s for (s,) in db.session.query(Outbound.slug).all() if s}
        slug, n = base, 1
        while slug in used:
            n += 1
            slug = f"{base}-{n}"
        return slug

    @staticmethod
    def id_by_slug(slug: str | None) -> int | None:
        if not slug:
            return None
        row = Outbound.query.filter(Outbound.slug == slug).first()
        return row.id if row else None

    @staticmethod
    def slug_by_id(outbound_id: int | None) -> str | None:
        if not outbound_id:
            return None
        row = db.session.get(Outbound, int(outbound_id))
        return row.slug if row else None

    def to_model(self) -> OutboundModel:
        from hiddifypanel.models.external_model.outbound import OutboundModel

        return OutboundModel.from_row(self)

    def to_dict(self) -> dict[str, Any]:
        return self.to_model().to_dict()

    @classmethod
    def bulk_register(cls, rows: Iterable[Any] = (), commit: bool = True, remove: bool = False) -> bool:
        """Create / update outbounds by slug (ids stay local). ``remove`` deletes the ones not listed. Returns whether anything changed."""
        from hiddifypanel.models.external_model import as_row
        from hiddifypanel.models.external_model.outbound import OutboundModel

        models = OutboundModel.coerce_many(as_row(r) for r in rows)
        # WARP, Direct and Block are one each, keyed by their mode: another panel's slug for them (or a repeated entry) must not add a copy.
        seen: set[OutboundMode] = set()
        unique = []
        for m in models:
            if m.mode in BUILTIN_MODES:
                if m.mode in seen:
                    continue
                seen.add(m.mode)
                if m.slug != str(m.mode):
                    m = m.model_copy(update={"slug": str(m.mode)})
            unique.append(m)
        models = unique
        existing = {r.slug: r for r in cls.query.all()}
        changed = False
        if remove:
            keep = {m.slug for m in models}
            for slug, row in existing.items():
                if slug not in keep:
                    db.session.delete(row)
                    changed = True
            db.session.flush()
        for m in models:
            row = existing.get(m.slug)
            if row is None:
                row = existing[m.slug] = cls(slug=m.slug)
                db.session.add(row)
                changed = True
            changed |= m.apply_to(row)
        db.session.flush()
        if commit:
            db.session.commit()
        return changed

    def __repr__(self) -> str:
        return f"<Outbound {self.id} {self.mode} {self.name!r}>"
